### ISSUE TITLE
Make find_func use rom_table_lookup_fn

### ISSUE THREAD

**Issue by ghost** [rp-rs/flash-algo#1]
Implement [find_func ](https://github.com/rp-rs/flash-algo/blob/d44d764c6fbe21ea901c3986f361419ba8e13a24/src/main.rs#L12)using [rom_table_lookup_fn](https://github.com/raspberrypi/pico-sdk/blob/26653ea81e340cacee55025d110c3e014a252a87/src/rp2_common/pico_bootrom/bootrom.c#L19)

**Comment by 9names** [comment]
Not going to do this, the current strategy works fine and doesn't couple the algo unnecessarily to a particular HAL.
