### ISSUE TITLE
Commit conventions

### ISSUE THREAD

**Issue by AsafFisher** [rp-rs/flash-algo#4]
The commit conventions should be as follows:

`project_component: module/file: comment`

For example:

_build: Travis.yml: Add new CI job_

**Comment by devsnek** [comment]
can the "module/file" bit be removed? commits already tell you which files have been modified right in the message.

**Comment by AsafFisher** [comment]
Maybe the `file` but not the module.
For example:
`OSX: arch: Implement ....`

P.S. I don't work at apple.

**Comment by johnbatty** [comment]
I also think that module/file is unnecessary - the file path gives you that.
Better to use those chars for a good description of the change.

There's good advice on writing git commit messages here:
https://chris.beams.io/posts/git-commit/

**Comment by AsafFisher** [comment]
The thing is that it looks better when you do `glog` for example. I know that you can understand from the path but it makes stuff easier to understand on a bigger perspective

**Comment by AsafFisher** [comment]
The idea is to not need to do `git log` to understand the context of the commit.. That is why the module/file is necessary

**Comment by 9names** [comment]
Won't fix. For a project of this size an ad-hoc commit message strategy is fine.
